name: 'Shopware Account Plugin Github Action'
description: 'Plugin Actions with Shopware Account.'
author: 'webpiloten.'

inputs:
  version:
    description: 'Release version of FroshPluginUploader'
    required: false
    default: '0.3.11'
  command:
    description: 'Commands available: validate | update | upload'
    required: true

runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/frosh-plugin-uploader.sh ${{ inputs.version }} ${{ inputs.command }} ${{ github.event.repository.name }}
      shell: bash
